# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-machines = {
    pname = "cockpit-machines";
    version = "346";
    src = fetchTarball {
      url = "https://github.com/cockpit-project/cockpit-machines/releases/download/346/cockpit-machines-346.tar.xz";
      sha256 = "sha256-Hc3M4JB+RHzABIKRQtvD4SyErh4CbY2ZV69lLerZDvw=";
    };
  };
}
