# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cockpit-machines = {
    pname = "cockpit-machines";
    version = "356";
    src = fetchTarball {
      url = "https://github.com/cockpit-project/cockpit-machines/releases/download/356/cockpit-machines-356.tar.xz";
      sha256 = "sha256-dRw7pscecVmWQJoGzI21IbL9N8+2pt3YhM6kr+RKAFA=";
    };
  };
}
