# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cockpit-machines = {
    pname = "cockpit-machines";
    version = "352";
    src = fetchTarball {
      url = "https://github.com/cockpit-project/cockpit-machines/releases/download/352/cockpit-machines-352.tar.xz";
      sha256 = "sha256-1jM1W5o4OWwkMozC+axwQwuDNV0qZ2fekzlftnrnaHA=";
    };
  };
}
